# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  schedule:
    - cron: '0 0 * * * *'
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: 'browser name'
        default: 'chrome'
      testname:
        type: string
        description: 'test name'
      xmlname:
        type: string
        description: 'xml name'
        default: 'testng.xml'

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with xml name
      if: ${{ inputs.xmlname }}
      run: >
        mvn clean test
        -DsuiteXmlFiles=${{ inputs.xmlname }}
        -Dmaven.test.failure.ignore=true
    - name: Build with maven
      if: ${{inputs.testname}}
      run: >
        mvn clean test
        -Dtest=${{ inputs.testname }}
        -Dbrowser=${{ inputs.browsername }}
        -Dmaven.test.failure.ignore=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spark-html
        path: ./reports/extentreport.html